package com.frostfel.animelist.data.migrations

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.frostfel.animelist.data.storage.AppDatabase
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Test
import org.junit.runner.RunWith

/** Opens a database created by the released app (version 2) with the current Room setup. */
@RunWith(AndroidJUnit4::class)
class MigrationTest {
    private val context = ApplicationProvider.getApplicationContext<Context>()
    private val name = "migration-test.db"

    @Test
    fun migrate2To3KeepsAnimeAndFavourites() = runTest {
        context.deleteDatabase(name)
        SQLiteDatabase.openOrCreateDatabase(context.getDatabasePath(name).apply { parentFile?.mkdirs() }, null).use { db ->
            V2_SCHEMA.forEach(db::execSQL)
            db.execSQL(
                """INSERT INTO Anime VALUES (52991, NULL, '{"jpg":{"image_url":"a","small_image_url":"a","large_image_url":"a"},"webp":{"image_url":"a","small_image_url":"a","large_image_url":"a"}}',
                '{}', 'Frieren', NULL, NULL, '[]', 'TV', NULL, 28, 'Currently Airing', 1,
                '{"from":"2026-10-02T00:00:00+00:00"}', NULL, NULL, 9.3, 1, 1, 1, 1, 1, NULL, NULL, 'fall', '2026',
                '{"day":"Fridays","time":"23:00","timezone":"Asia/Tokyo"}', '[]', '[]', '[]', '[]', '[]', '[]', '[]', 0, 1)"""
            )
            db.execSQL("INSERT INTO user_anime_preferences VALUES (52991, 1, 123)")
            db.execSQL("INSERT INTO RemoteKey VALUES ('52991', NULL, 2, 1, 0, 52991)")
            db.version = 2
        }

        val room = Room.databaseBuilder(context, AppDatabase::class.java, name)
            .addMigrations(MIGRATION_1_2, MIGRATION_2_3)
            .build()
        val favourites = room.animeDao().getAllFav()
        assertEquals(listOf("Frieren"), favourites.map { it.anime.title })
        assertEquals("Fridays", favourites.single().anime.broadcast.day)

        room.openHelper.readableDatabase
            .query("SELECT name FROM sqlite_master WHERE type='table' AND name='RemoteKey'")
            .use { assertFalse(it.moveToFirst()) }
        room.close()
    }

    private companion object {
        // Schema generated by Room for version 2 (app 1.7).
        val V2_SCHEMA = listOf(
            "CREATE TABLE IF NOT EXISTS `Anime` (`malId` INTEGER NOT NULL, `url` TEXT, `images` TEXT NOT NULL, `trailer` TEXT NOT NULL, `title` TEXT, `titleEnglish` TEXT, `titleJapanese` TEXT, `titleSynonyms` TEXT NOT NULL, `type` TEXT, `source` TEXT, `episodes` INTEGER NOT NULL, `status` TEXT, `airing` INTEGER NOT NULL, `aired` TEXT NOT NULL, `duration` TEXT, `rating` TEXT, `score` REAL NOT NULL, `scoredBy` INTEGER NOT NULL, `rank` INTEGER NOT NULL, `popularity` INTEGER NOT NULL, `members` INTEGER NOT NULL, `favorites` INTEGER NOT NULL, `synopsis` TEXT, `background` TEXT, `season` TEXT, `year` TEXT, `broadcast` TEXT NOT NULL, `producers` TEXT NOT NULL, `licensors` TEXT NOT NULL, `studios` TEXT NOT NULL, `genres` TEXT NOT NULL, `explicitGenres` TEXT NOT NULL, `themes` TEXT NOT NULL, `demographics` TEXT NOT NULL, `starred` INTEGER NOT NULL, `page` INTEGER NOT NULL, PRIMARY KEY(`malId`))",
            "CREATE TABLE IF NOT EXISTS `RemoteKey` (`id` TEXT NOT NULL, `prevKey` INTEGER, `nextKey` INTEGER, `currentPage` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, `animeId` INTEGER NOT NULL, PRIMARY KEY(`id`))",
            "CREATE TABLE IF NOT EXISTS `user_anime_preferences` (`malId` INTEGER NOT NULL, `starred` INTEGER NOT NULL DEFAULT 0, `starredAt` INTEGER, PRIMARY KEY(`malId`))",
            "CREATE TABLE IF NOT EXISTS room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT)",
            "INSERT OR REPLACE INTO room_master_table (id,identity_hash) VALUES(42, '41647b355e1dbb69403bbe654bc33568')",
        )
    }
}
